### PR TITLE
Rename Bundle to DataDefinitionsBundle

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
- Rename JS Namespaces to pimcore.plugin.datadefinitions
- Rename ImportDefinition Resource to import_definition
- Add BC Layer for PHP Classes
- Add BC Layer for JS Extensions like Getters, Interpreters, etc.
- Add BC Layer for Service Names
- Add BC Layer for import_definition resource

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
@dkarlovi @aarongerig could you please review it, or better test it on a Pimcore 5 Production Ready Setup. This is a huge change, but everything should be BC for now:

 - ClassNames
 - Services
 - JavaScript Files

**Comment by dkarlovi** [comment]
I can do it no sooner than Saturday, sorry.

**Comment by dpfaffenbauer** [comment]
thats fine. Since it is a huge PR, it should also take some time for testing

**Comment by aarongerig** [comment]
@dpfaffenbauer Sure, will do. One thing I see already is the namespace, which should be changed to `Wvision\Bundle\...` instead of `WVision\Bundle\...`. All other w-vision bundles are using the first version.

**Comment by dpfaffenbauer** [comment]
@aarongerig done

**Comment by dkarlovi** [comment]
Composer package, Git repo not renamed?

**Comment by dpfaffenbauer** [comment]
repo will be.
Package Name with 3.0 release to keep BC

**Comment by dkarlovi** [comment]
Well, you can already change it since this is going to master, which will be 3.0.

**Comment by dpfaffenbauer** [comment]
true, but this should be merged into 2.3

**Comment by dkarlovi** [comment]
OK, fair enough.

I'm getting this error currently:

```
$ bin/dsh bin/console cache:clear
PHP Warning:  Uncaught RuntimeException: The autoloader expected class "ImportDefinitionsBundle\Model\Mapping" to be defined in file "/var/www/html/vendor/composer/../w-vision/import-definitions/src/ImportDefinitionsBundle/Model/Mapping.php". The file was found but the class was not in it, the class name or namespace probably has a typo. in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php:213
Stack trace:
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php(166): Symfony\Component\Debug\DebugClassLoader->checkClass('ImportDefinitio...', '/var/www/html/v...')
#1 [internal function]: Symfony\Component\Debug\DebugClassLoader->loadClass('ImportDefinitio...')
#2 /var/www/html/src/AppBundle/ImportDefinitions/Interpreter/AssetDownloadUrlInterpreter.php(13): spl_autoload_call('ImportDefinitio...')
#3 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php(156): require('/var/www/html/s...')
#4 [internal function]: Symfony\Compone in /var/www/html/src/AppBundle/ImportDefinitions/Interpreter/AssetDownloadUrlInterpreter.php on line 13

Warning: Uncaught RuntimeException: The autoloader expected class "ImportDefinitionsBundle\Model\Mapping" to be defined in file "/var/www/html/vendor/composer/../w-vision/import-definitions/src/ImportDefinitionsBundle/Model/Mapping.php". The file was found but the class was not in it, the class name or namespace probably has a typo. in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php:213
Stack trace:
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php(166): Symfony\Component\Debug\DebugClassLoader->checkClass('ImportDefinitio...', '/var/www/html/v...')
#1 [internal function]: Symfony\Component\Debug\DebugClassLoader->loadClass('ImportDefinitio...')
#2 /var/www/html/src/AppBundle/ImportDefinitions/Interpreter/AssetDownloadUrlInterpreter.php(13): spl_autoload_call('ImportDefinitio...')
#3 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php(156): require('/var/www/html/s...')
#4 [internal function]: Symfony\Compone in /var/www/html/src/AppBundle/ImportDefinitions/Interpreter/AssetDownloadUrlInterpreter.php on line 13
PHP Fatal error:  Declaration of AppBundle\ImportDefinitions\Interpreter\AssetDownloadUrlInterpreter::interpret(Pimcore\Model\DataObject\Concrete $object, $value, ImportDefinitionsBundle\Model\Mapping $map, $data, ImportDefinitionsBundle\Model\DefinitionInterface $definition, $params, $configuration) must be compatible with Wvision\Bundle\DataDefinitionsBundle\Interpreter\InterpreterInterface::interpret(Pimcore\Model\DataObject\Concrete $object, $value, Wvision\Bundle\DataDefinitionsBundle\Model\Mapping $map, $data, Wvision\Bundle\DataDefinitionsBundle\Model\DefinitionInterface $definition, $params, $configuration) in /var/www/html/src/AppBundle/ImportDefinitions/Interpreter/AssetDownloadUrlInterpreter.php on line 13

Fatal error: Declaration of AppBundle\ImportDefinitions\Interpreter\AssetDownloadUrlInterpreter::interpret(Pimcore\Model\DataObject\Concrete $object, $value, ImportDefinitionsBundle\Model\Mapping $map, $data, ImportDefinitionsBundle\Model\DefinitionInterface $definition, $params, $configuration) must be compatible with Wvision\Bundle\DataDefinitionsBundle\Interpreter\InterpreterInterface::interpret(Pimcore\Model\DataObject\Concrete $object, $value, Wvision\Bundle\DataDefinitionsBundle\Model\Mapping $map, $data, Wvision\Bundle\DataDefinitionsBundle\Model\DefinitionInterface $definition, $params, $configuration) in /var/www/html/src/AppBundle/ImportDefinitions/Interpreter/AssetDownloadUrlInterpreter.php on line 13
```

**Comment by dkarlovi** [comment]
The BC layer doesn't define previous interfaces if the new code is also present, but they will be present side by side for a while, no?

**Comment by aarongerig** [comment]
Ok, just finished testing. Runs pretty solid. 👍 
Although, here are a few things that came up.

- When defining email documents (success / failure) only the ID is shown inside the field. I think displaying the full path would be better and that's pimcore standard anyway.
- Sending those emails doesn't work either.
```log
In Mail.php line 630: - Expected response code 220 but got an empty response
```
- Console Commands are not renamed yet, e.g. `data-definitions:import:run` or `data-definitions:export:run`. According to @dpfaffenbauer this will be done, once version 3.0 will be released.
- Many interfaces (e.g. `InterpreterInterface`) demand deprecated classes/interfaces to be implemented, for example `DefinitionInterface` instead of `DataDefinitionInterface`.
- Naming inconsistencies for tags `data_definitions.provider` / `data_definitions.export_provider`
- The tags `import_definition.runner`, `data_definitions.runner` and `data_definitons.filter` don't show up in my IDE for auto completion, even though they exist.
- When testing the provider settings through clicking the "Test" button a JS error is thrown and you have to reload the pimcore back-end to continue work.
```log
Ext.layout.container.Border.onAdd(): Cannot have multiple center regions in a BorderLayout
```
- Auto tag registering is not working, or at least it didn't work for me. Implemented the interfaces, but the interpreter didn't show up in the list of available interpreters.

That's it. :)

**Comment by aarongerig** [comment]
Oh and thank's for testing as well, @dkarlovi !

**Comment by dpfaffenbauer** [comment]
> * When defining email documents (success / failure) only the ID is shown inside the field. I think displaying the full path would be better and that's pimcore standard anyway.

Propably has nothing to do with this PR, can you create a separate issues pls?

> * Sending those emails doesn't work either.
> 
> ```
> In Mail.php line 630: - Expected response code 220 but got an empty response
> ```

Same as above

> 
> * Console Commands are not renamed yet, e.g. `data-definitions:import:run` or `data-definitions:export:run`. According to @dpfaffenbauer this will be done, once version 3.0 will be released.

Yep, to keep BC for the 2.3 release

> * Many interfaces (e.g. `InterpreterInterface`) demand deprecated classes/interfaces to be implemented, for example `DefinitionInterface` instead of `DataDefinitionInterface`.

Yep, to keep BC, this will be changed in 3.0 though. We want to have a smooth transition to the new name.

> * Naming inconsistencies for tags `data_definitions.provider` / `data_definitions.export_provider`

Don't get what you mean? Guess you meant `import_definition.provider` vs `data_definitions.import_provider`? We couldn't change the tag in < 2.3 cause of BC

> * The tags `import_definition.runner`, `data_definitions.runner` and `data_definitons.filter` don't show up in my IDE for auto completion, even though they exist.

Yep, cause PHP Storm only recognizes them if it already saw one, as for runners and filters, there is no "default" implementation

> * When testing the provider settings through clicking the "Test" button a JS error is thrown and you have to reload the pimcore back-end to continue work.
> 
> ```
> Ext.layout.container.Border.onAdd(): Cannot have multiple center regions in a BorderLayout
> ```

Propably has nothing to do with this PR, can you create a separate issues pls?

> 
> * Auto tag registering is not working, or at least it didn't work for me. Implemented the interfaces, but the interpreter didn't show up in the list of available interpreters.
> 
> That's it. :)

Works for me though:

```yml

AppBundle\ImportDefinitions\Interpreter\:
    resource: '../../ImportDefinitions/Interpreter'
    public: true
```

```php
<?php

namespace AppBundle\ImportDefinitions\Interpreter;

use Pimcore\Model\Asset;
use Pimcore\Model\DataObject\Concrete;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Wvision\Bundle\DataDefinitionsBundle\Interpreter\InterpreterInterface;
use Wvision\Bundle\DataDefinitionsBundle\Model\DefinitionInterface;
use Wvision\Bundle\DataDefinitionsBundle\Model\Mapping;

class SimpleInterpreter implements InterpreterInterface
{
    public function interpret(
        Concrete $object,
        $value,
        Mapping $map,
        $data,
        DefinitionInterface $definition,
        $params,
        $configuration
    ) {
        return $value;
    }
}
```

That one will get registered as `simple_provider`

**Comment by aarongerig** [comment]
> > * When defining email documents (success / failure) only the ID is shown inside the field. I think displaying the full path would be better and that's pimcore standard anyway.
> 
> Propably has nothing to do with this PR, can you create a separate issues pls?

Done, see #200 

> > * Sending those emails doesn't work either.
> > 
> > ```
> > In Mail.php line 630: - Expected response code 220 but got an empty response
> > ```
> 
> Same as above

Done, see #201

> > * Naming inconsistencies for tags `data_definitions.provider` / `data_definitions.export_provider`
> 
> Don't get what you mean? Guess you meant `import_definition.provider` vs `data_definitions.import_provider`? We couldn't change the tag in < 2.3 cause of BC

Just saw that, nevermind then.

> > * When testing the provider settings through clicking the "Test" button a JS error is thrown and you have to reload the pimcore back-end to continue work.
> > 
> > ```
> > Ext.layout.container.Border.onAdd(): Cannot have multiple center regions in a BorderLayout
> > ```
> 
> Propably has nothing to do with this PR, can you create a separate issues pls?

Done, see #202

> > * Auto tag registering is not working, or at least it didn't work for me. Implemented the interfaces, but the interpreter didn't show up in the list of available interpreters.
> > 
> > That's it. :)
> 
> Works for me though:
> 
> ```yaml
> AppBundle\ImportDefinitions\Interpreter\:
>     resource: '../../ImportDefinitions/Interpreter'
>     public: true
> ```
> 
> ```
> <?php
> 
> namespace AppBundle\ImportDefinitions\Interpreter;
> 
> use Pimcore\Model\Asset;
> use Pimcore\Model\DataObject\Concrete;
> use Symfony\Contracts\HttpClient\HttpClientInterface;
> use Wvision\Bundle\DataDefinitionsBundle\Interpreter\InterpreterInterface;
> use Wvision\Bundle\DataDefinitionsBundle\Model\DefinitionInterface;
> use Wvision\Bundle\DataDefinitionsBundle\Model\Mapping;
> 
> class SimpleInterpreter implements InterpreterInterface
> {
>     public function interpret(
>         Concrete $object,
>         $value,
>         Mapping $map,
>         $data,
>         DefinitionInterface $definition,
>         $params,
>         $configuration
>     ) {
>         return $value;
>     }
> }
> ```
> 
> That one will get registered as `simple_provider`

I missed the .yml part.

**Comment by dpfaffenbauer** [comment]
BTW: @dkarlovi master currently is 2.3 and not 3.0. so, it merges into the right branch

**Comment by dpfaffenbauer** [comment]
@aarongerig @dkarlovi happy to merge this?

**Comment by dkarlovi** [comment]
Yes for me too, let's do it, eventual issues can always be fixed in 2.3.1 😀

**Pull request merged**
